//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 10:49:30 PM EST 
//


package com.commonsemantics.olina.plugin.connector.pubmed.dtd150101.xml;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "medlineCitation",
    "deleteCitation"
})
@XmlRootElement(name = "MedlineCitationSet")
public class MedlineCitationSet {

    @XmlElement(name = "MedlineCitation")
    protected List<MedlineCitation> medlineCitation;
    @XmlElement(name = "DeleteCitation")
    protected DeleteCitation deleteCitation;

    /**
     * Gets the value of the medlineCitation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medlineCitation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMedlineCitation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedlineCitation }
     * 
     * 
     */
    public List<MedlineCitation> getMedlineCitation() {
        if (medlineCitation == null) {
            medlineCitation = new ArrayList<MedlineCitation>();
        }
        return this.medlineCitation;
    }

    /**
     * Gets the value of the deleteCitation property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteCitation }
     *     
     */
    public DeleteCitation getDeleteCitation() {
        return deleteCitation;
    }

    /**
     * Sets the value of the deleteCitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteCitation }
     *     
     */
    public void setDeleteCitation(DeleteCitation value) {
        this.deleteCitation = value;
    }

}
